version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/scripts:/scripts
      - ./db/scripts/entrypoint:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - ./db/.env
    environment:
      - TZ=Asia/Bangkok
      - LANG=C.UTF-8

  backend:
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/uploads
    env_file:
      - ./backend/.env
    restart: on-failure
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=oasip

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/us3/api
        - BASE_URL=/us3
    depends_on:
      - backend

  reverse_proxy:
    build: ./reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
